package it.ding.webdriver;

public enum Platform {

    CHROME_DESKTOP_LOCAL,
    PIXEL2_EMULATOR_LOCAL,
    IPHONEX_SIMULATOR_LOCAL,
    CHROME_DESKTOP_CLOUD,
    FIREFOX_DESKTOP_CLOUD,
    SAMSUNG_GALAXY_S9_EMULATOR_CLOUD
}
