package it.ding.webdriver;

public enum Platform {

    CHROME_DESKTOP_LOCAL,
    PIXEL2_EMULATOR_LOCAL,
    IPHONEX_SIMULATOR_LOCAL,
    CHROME_DESKTOP_CLOUD,
    FIREFOX_DESKTOP_CLOUD,
    GALAXYS9_EMULATOR_CLOUD,
    NEXUS5X_RDC,
    IPHONE6_RDC
}
